sudo: false
language: python
services:
  - docker

before_install:
  - docker run -d --hostname rabbitmq --name rabbitmq -p 15672:15672 -p 5672:5672 -e RABBITMQ_DEFAULT_USER=guest -e RABBITMQ_DEFAULT_PASS=guest rabbitmq:3-management

install:
  - pip install tox

matrix:
  include:
    - stage: static
      python: 3.6
      env: TOX_ENV=static
    - stage: test
      python: 3.5
      env: TOX_ENV=py35-test
    - stage: test
      python: 3.6
      env: TOX_ENV=py36-test
    - stage: test
      python: 3.7
      # dist: xenial
      sudo: true
      env: TOX_ENV=py37-test
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: mattbennett
        password:
          secure: "uBt91tS3ZxLdffr/hCv/3Sm6xbWJmiE9cUrvGIbYNS4CW2LHD5Kyij6KI3Zn2g6GdZYRWeqrgtHVUJq+VkzfE/ejThsBYDLsIQYxKTM/L6uL3R3TnZXg2eUWXiaFuz9TOLuX+iLdYwIO+uBAl/DwRzp4QfZYlWnpR0tC4PDGdnm5epFooNqPqCak/9+oym/22YVY76qw5ajpsWlm77glvi+DoNaBYFs8YGw5ud/2q+pquAtYKBocSQ9a9cZKRCyOrKEa+x4okb3ulXMyfZHXOwS8HZ2Bndtk75sTwpN0UiAO4gI5G7fl0mQJrVmKleE1rc7eaPmhBc2snOvzV8LCVJ9PCpG6MVYtx+lX4FjWYLUnOGF099aZz/Y1wfUi4ulvXKBrA7iEgCHR6An+LAQYv+BW78G955NhWasNu0YpZHrhNTzPGaXLKhWvmfoPtmQPjcHmt05OGU9A4inX5muHbKohQQdIQp03r8mCsQGKgW/vzm74Umpxu6RFvqc2vfNmYHf6uZfoP/I746EFLFFQ3tHNfQJllEnAezPTeBk6maT/J0mHWcipbRNq8PDaGkwHU7I35N4nmIo80rBJ1QDqERz0dG4YkJo5bV/DYq2XLRrut4sXy+LMjkPa1C/ehTLsk+6HhRDPD4uqh7PUcG1yJWSEyHp7Veg7wBRm8PRvcsA="
        on:
          tags: true
          repo: nameko/nameko-grpc
        distributions: "sdist bdist_wheel"


script:
  - tox -e $TOX_ENV
